"""AACT (Aggregate Analysis of ClinicalTrials.gov) study metadata reference for DECLARE-TIMI 58 (NCT01986881).

Provides real-world clinical trial facility profiles, study metadata, and investigator
details based on the public CTTI AACT database.
"""

from typing import List, Dict, Any

# CTTI AACT trial identity for DECLARE-TIMI 58
AACT_TRIAL_METADATA = {
    "nct_id": "NCT01986881",
    "brief_title": "Multicenter Trial to Evaluate the Effect of Dapagliflozin on the Incidence of Cardiovascular Events (DECLARE - TIMI 58)",
    "official_title": "A Phase III, Multicenter, Randomized, Double-Blind, Placebo-Controlled Trial to Evaluate the Effect of Dapagliflozin 10 mg Once Daily on the Incidence of Cardiovascular Death, Myocardial Infarction or Ischemic Stroke in Patients With Type 2 Diabetes",
    "study_type": "Interventional",
    "phase": "Phase 3",
    "overall_status": "Completed",
    "start_date": "2013-11-01",
    "completion_date": "2018-09-18",
    "lead_sponsor": "AstraZeneca",
    "collaborator": "TIMI Study Group",
    "source_url": "https://aact.ctti-clinicaltrials.org/",
}

# The 10 trial center profiles mapped to AACT international study locations and Section J risk specifications
AACT_SITES_REFERENCE: List[Dict[str, Any]] = [
    {
        "site_id": "SITE-101",
        "site_code": "101",
        "site_name": "Metro Clinical Research Institute",
        "city": "New York",
        "state": "NY",
        "country": "United States",
        "investigator": "Dr. Stephen Wiviott, MD",
        "activation_date": "2013-11-15",
        "target_risk_level": "low",
        "notes": "Top-tier academic medical center. Exceptional protocol compliance.",
    },
    {
        "site_id": "SITE-102",
        "site_code": "102",
        "site_name": "Westside Clinical Research Center",
        "city": "Los Angeles",
        "state": "CA",
        "country": "United States",
        "investigator": "Dr. David A. Morrow, MD",
        "activation_date": "2013-12-01",
        "target_risk_level": "medium",
        "notes": "High patient volume, chronic data entry delays (PROC-003 lag).",
    },
    {
        "site_id": "SITE-103",
        "site_code": "103",
        "site_name": "Central Heart & Vascular Trials",
        "city": "Chicago",
        "state": "IL",
        "country": "United States",
        "investigator": "Dr. Eugene Braunwald, MD",
        "activation_date": "2013-11-20",
        "target_risk_level": "low",
        "notes": "Excellent clinical practice, pristine audit record.",
    },
    {
        "site_id": "SITE-104",
        "site_code": "104",
        "site_name": "City General Hospital Clinical Trial Unit",
        "city": "Houston",
        "state": "TX",
        "country": "United States",
        "investigator": "Dr. Marc S. Sabatine, MD",
        "activation_date": "2014-01-10",
        "target_risk_level": "high",
        "notes": "High-risk site: Staff turnover, multiple major dosing deviations, unnotified prohibited meds, missed safety visits.",
    },
    {
        "site_id": "SITE-105",
        "site_code": "105",
        "site_name": "Northgate Medical Research",
        "city": "Boston",
        "state": "MA",
        "country": "United States",
        "investigator": "Dr. Deepak L. Bhatt, MD",
        "activation_date": "2013-12-15",
        "target_risk_level": "medium",
        "notes": "Medium-risk site: Screening eligibility lab exception, delayed amendment re-consent.",
    },
    {
        "site_id": "SITE-106",
        "site_code": "106",
        "site_name": "Riverside Cardiovascular Institute",
        "city": "London",
        "state": "England",
        "country": "United Kingdom",
        "investigator": "Dr. Keith A.A. Fox, MB ChB",
        "activation_date": "2014-02-01",
        "target_risk_level": "low",
        "notes": "UK coordinating center. Full ICH E6 GCP compliance.",
    },
    {
        "site_id": "SITE-107",
        "site_code": "107",
        "site_name": "North Medical Center Diabetes Trials",
        "city": "Toronto",
        "state": "ON",
        "country": "Canada",
        "investigator": "Dr. Lawrence A. Leiter, MD",
        "activation_date": "2014-01-20",
        "target_risk_level": "medium",
        "notes": "Medium-risk site: Unapproved warfarin concomitant therapy, multiple missed follow-up visits.",
    },
    {
        "site_id": "SITE-108",
        "site_code": "108",
        "site_name": "Southern Research Trials Foundation",
        "city": "Sydney",
        "state": "NSW",
        "country": "Australia",
        "investigator": "Dr. John Amerena, MBBS",
        "activation_date": "2014-02-15",
        "target_risk_level": "low",
        "notes": "Australian lead center. Outstanding retention and GCP adherence.",
    },
    {
        "site_id": "SITE-109",
        "site_code": "109",
        "site_name": "Pacific Medical Trials Institute",
        "city": "Tokyo",
        "state": "Tokyo",
        "country": "Japan",
        "investigator": "Dr. Hiroshi Ito, MD, PhD",
        "activation_date": "2014-03-01",
        "target_risk_level": "low",
        "notes": "Japan regulatory lead center. Zero critical deviations.",
    },
    {
        "site_id": "SITE-110",
        "site_code": "110",
        "site_name": "Alpine Clinical Research Center",
        "city": "Zurich",
        "state": "ZH",
        "country": "Switzerland",
        "investigator": "Dr. Thomas F. Lüscher, MD",
        "activation_date": "2014-02-10",
        "target_risk_level": "medium",
        "notes": "Medium-risk site: Visit window shifts due to patient holiday schedules, missing intermediate labs.",
    },
]
