"""
src/backend/schemas.py
──────────────────────
Pydantic v2 request/response schemas for the AI endpoints.

These schemas define the HTTP boundary layer only.  The AI domain
dataclasses (ExtractedRule, SiteRiskContext, DeviationDetail, etc.)
are NOT duplicated here — they are constructed from the incoming
request data and their .to_dict() output is serialised for responses.

Architecture contract
─────────────────────
• /ai/extract-protocol  — status is ALWAYS "pending" in every rule
• /ai/explain-risk      — risk_score / risk_level are passed IN verbatim;
                          the AI layer does NOT recalculate them
• /ai/generate-capa     — response always carries human_review_required=True
                          and status="draft"; CAPA is never auto-approved
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# /ai/extract-protocol
# ---------------------------------------------------------------------------


class ExtractProtocolRequest(BaseModel):
    """Request body for POST /ai/extract-protocol."""

    protocol_text: str = Field(
        ...,
        min_length=1,
        description="Raw text of the clinical trial protocol (from PDF, AACT, etc.).",
        examples=["Subjects must receive Study Drug A at 10 mg orally once daily."],
    )

    @field_validator("protocol_text")
    @classmethod
    def not_whitespace_only(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("protocol_text must not be empty or whitespace-only.")
        return v


class ExtractProtocolResponse(BaseModel):
    """
    Response for POST /ai/extract-protocol.

    human_review_required is always True — extracted rules must be reviewed
    and approved before the deterministic rule engine may use them.
    """

    rule_count: int
    protocol_id: str
    rules: list[dict[str, Any]]
    warnings: list[str]
    human_review_required: bool = True
    message: str = (
        "Extraction complete. All rules have status='pending' and require "
        "human review before activation in the rule engine."
    )


# ---------------------------------------------------------------------------
# /ai/explain-risk — input sub-schemas
# ---------------------------------------------------------------------------


class DeviationSummarySchema(BaseModel):
    """
    A single deviation already detected and classified by the rule engine.

    All fields are FACTS from the deterministic engine.  The AI layer
    receives them read-only and must not alter severity or risk scores.
    """

    deviation_id: str = Field(..., min_length=1)
    rule_id: str = Field(..., min_length=1)
    category: str = Field(..., min_length=1)
    severity: str = Field(
        ...,
        description="Assigned by the rule engine: minor | major | critical",
    )
    description: str = Field(..., min_length=1)
    visit: str = ""
    affected_patients: int = Field(default=0, ge=0)
    occurrence_count: int = Field(default=0, ge=0)


class ExplainRiskRequest(BaseModel):
    """
    Request body for POST /ai/explain-risk.

    risk_score and risk_level are COMPUTED BY THE RULE ENGINE and passed in
    here verbatim.  This endpoint never calculates or modifies those values.
    """

    site_id: str = Field(..., min_length=1)
    site_name: str = ""
    risk_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Pre-computed risk score from the deterministic rule engine (0–100).",
    )
    risk_level: str = Field(
        ...,
        description="Pre-computed risk level from the rule engine: low | medium | high | critical",
    )
    total_patients: int = Field(..., ge=0)
    deviations: list[DeviationSummarySchema] = Field(
        default_factory=list,
        description="Deviation facts already determined by the rule engine.",
    )
    protocol_title: str = ""
    observation_period_days: int = Field(default=0, ge=0)

    @field_validator("risk_level")
    @classmethod
    def valid_risk_level(cls, v: str) -> str:
        allowed = {"low", "medium", "high", "critical"}
        if v.lower() not in allowed:
            raise ValueError(f"risk_level must be one of {sorted(allowed)}, got {v!r}.")
        return v.lower()


class ExplainRiskResponse(BaseModel):
    """Response for POST /ai/explain-risk."""

    site_id: str
    risk_score: float
    risk_level: str
    explanation: str
    key_findings: list[str]
    recommended_focus: str
    message: str = (
        "Risk explanation generated by IBM watsonx.ai based on pre-computed "
        "scores from the deterministic rule engine. For informational use only."
    )


# ---------------------------------------------------------------------------
# /ai/generate-capa
# ---------------------------------------------------------------------------


class GenerateCapaRequest(BaseModel):
    """
    Request body for POST /ai/generate-capa.

    All deviation facts (severity, category, rule_id) are CONFIRMED by the
    deterministic rule engine before being passed here.
    """

    deviation_id: str = Field(..., min_length=1)
    rule_id: str = Field(..., min_length=1)
    category: str = Field(
        ...,
        description=(
            "Deviation category: dosing | visit_window | lab | eligibility | "
            "medication | procedure | safety | other"
        ),
    )
    severity: str = Field(
        ...,
        description="Assigned by rule engine: minor | major | critical",
    )
    description: str = Field(..., min_length=1)
    protocol_requirement: str = Field(..., min_length=1)
    site_id: str = Field(..., min_length=1)
    site_name: str = ""
    affected_patients: int = Field(default=0, ge=0)
    occurrence_count: int = Field(default=0, ge=0)
    visit: str = ""
    detection_date: str = ""
    protocol_title: str = ""
    additional_context: str = ""

    @field_validator("severity")
    @classmethod
    def valid_severity(cls, v: str) -> str:
        allowed = {"minor", "major", "critical"}
        if v.lower() not in allowed:
            raise ValueError(f"severity must be one of {sorted(allowed)}, got {v!r}.")
        return v.lower()

    @field_validator("category")
    @classmethod
    def valid_category(cls, v: str) -> str:
        allowed = {
            "dosing", "visit_window", "lab", "eligibility",
            "medication", "procedure", "safety", "other",
        }
        if v.lower() not in allowed:
            raise ValueError(f"category must be one of {sorted(allowed)}, got {v!r}.")
        return v.lower()


class GenerateCapaResponse(BaseModel):
    """
    Response for POST /ai/generate-capa.

    human_review_required is always True.
    status is always "draft" — the CAPA is NEVER auto-approved.
    """

    capa_id: str | None = None
    deviation_id: str
    status: str = "draft"
    human_review_required: bool = True
    root_cause_analysis: str
    immediate_actions: list[str]
    preventive_actions: list[str]
    timeline: list[str]
    effectiveness_check: str
    full_draft: str
    warnings: list[str]
    message: str = (
        "This CAPA document is an AI-generated DRAFT. It must be reviewed and "
        "approved by a qualified clinical operations professional before any "
        "regulatory submission. The AI has not modified deviation severity or "
        "determined whether the deviation occurred."
    )


# ---------------------------------------------------------------------------
# POST /run-engine  — Member 1 pipeline execution
# ---------------------------------------------------------------------------


class RunEngineRequest(BaseModel):
    """
    Request body for POST /run-engine.

    Controls how much synthetic data the data generator produces.
    Smaller values (num_sites=3, patients_per_site=3) complete quickly
    for demo/testing purposes.  Use larger values for realistic load.
    """

    num_sites: int = Field(
        default=5,
        ge=1,
        le=50,
        description="Number of trial sites to generate (1–50).",
    )
    patients_per_site: int = Field(
        default=5,
        ge=1,
        le=50,
        description="Patients per site (1–50).",
    )
    random_seed: int = Field(
        default=42,
        description="RNG seed for reproducible dataset generation.",
    )
    protocol_id: str | None = Field(
        default=None,
        description="Optional protocol ID to filter rules. If not provided, the default protocol is used.",
    )


class SiteRiskSummary(BaseModel):
    """Per-site risk summary included in the RunEngineResponse."""

    site_id: str
    risk_score: float = Field(
        description=(
            "Deterministic risk score computed by score_all_sites(). "
            "0–100. Never set by AI."
        )
    )
    risk_level: str = Field(
        description=(
            "Risk level band: LOW | MEDIUM | HIGH.  "
            "Computed by the rule engine threshold logic only."
        )
    )
    total_deviations: int
    major_count: int
    minor_count: int
    top_risk_drivers: list[str] = []


class RunEngineResponse(BaseModel):
    """
    Response for POST /run-engine.

    Contains a summary of the pipeline execution and per-site risk scores.
    The site_risk_scores list provides the pre-computed facts that the
    Member 2 /ai/explain-risk and /ai/generate-capa endpoints expect as input.
    """

    run_id: str
    started_at: str
    completed_at: str
    status: str
    sites_count: int
    patients_count: int
    deviations_detected: int = Field(
        description="Number of protocol deviations detected by the rule engine."
    )
    sites_scored: int
    high_risk_sites: int
    site_risk_scores: list[Any] = Field(
        description=(
            "Per-site risk scores computed by score_all_sites(). "
            "Pass risk_score and risk_level verbatim to /ai/explain-risk."
        )
    )
    deviation_sample: list[Any] = Field(
        description="Up to 10 sample detected deviations for inspection."
    )
    error_message: str | None = None
    message: str = (
        "Rule engine pipeline completed. All risk scores and severities are "
        "deterministic outputs of TrialGuardRuleEngine — not computed by AI. "
        "Pass site_risk_scores entries to POST /ai/explain-risk to generate "
        "natural-language explanations, or deviation entries to "
        "POST /ai/generate-capa to draft CAPA documents."
    )
